export enum ActionType {
  SEARCH_WIKI_BEGIN = "SEARCH_WIKI_BEGIN",
  SEARCH_WIKI_SUCCESS = "SEARCH_WIKI_SUCCESS",
  SEARCH_WIKI_ERROR = "SEARCH_WIKI_ERROR",
  CLOSE_DROPDOWN = "CLOSE_DROPDOWN",
  CLEAR_ALERT = "CLEAR_ALERT",
  GET_SUMMARY_BEGIN = "GET_SUMMARY_BEGIN",
  GET_SUMMARY_SUCCESS = "GET_SUMMARY_SUCCESS",
  GET_SUMMARY_ERROR = "GET_SUMMARY_ERROR",
  SET_BKG_PALETTE = "SET_BKG_PALETTE",
  SHOW_MODAL = "SHOW_MODAL",
  HIDE_MODAL = "HIDE_MODAL",
}
